name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  provider: ^6.1.4
  intl: ^0.18.0
  table_calendar: ^3.0.8
  google_fonts: ^6.2.1
  flutter_gemini: ^3.0.0
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.0.0
  emoji_picker_flutter: ^1.6.2
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar1.jpg
    - assets/avatar2.jpg
    - assets/avatar3.jpg 
    - assets/avatar4.jpg
    - assets/avatar5.jpg
    - assets/avatar6.jpg
    - assets/avatar7.jpg
    - assets/avatar8.jpg
    - assets/avatar9.jpg
    - assets/avatar10.jpg
   
