// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgE0R2W2RK3pIqqjulP5VKFHiAQvOlouI',
    appId: '1:1042141812512:web:75e73ab9ec17df5985a945',
    messagingSenderId: '1042141812512',
    projectId: 'rommate-4c226',
    authDomain: 'rommate-4c226.firebaseapp.com',
    storageBucket: 'rommate-4c226.firebasestorage.app',
    measurementId: 'G-CGYHSV7CD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF0giw-_NgfIPc2dL1QwTWV_JMhE3r9Xk',
    appId: '1:1042141812512:android:a9cb48f60a1a3da085a945',
    messagingSenderId: '1042141812512',
    projectId: 'rommate-4c226',
    storageBucket: 'rommate-4c226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7tj5D_22SIjPHldUssBI1OJvi9rmD3s',
    appId: '1:1042141812512:ios:13a154e6723c3d9e85a945',
    messagingSenderId: '1042141812512',
    projectId: 'rommate-4c226',
    storageBucket: 'rommate-4c226.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg7tj5D_22SIjPHldUssBI1OJvi9rmD3s',
    appId: '1:1042141812512:ios:13a154e6723c3d9e85a945',
    messagingSenderId: '1042141812512',
    projectId: 'rommate-4c226',
    storageBucket: 'rommate-4c226.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgE0R2W2RK3pIqqjulP5VKFHiAQvOlouI',
    appId: '1:1042141812512:web:c5dc5a6d0aa743e285a945',
    messagingSenderId: '1042141812512',
    projectId: 'rommate-4c226',
    authDomain: 'rommate-4c226.firebaseapp.com',
    storageBucket: 'rommate-4c226.firebasestorage.app',
    measurementId: 'G-60WWX109C5',
  );

}